OpenWrt 24.10 support
## Overview
* OpenWrt 24.10 fixes
  * The service now explicitly destroys meter sets used for the threaded client/server detection as these were causing failures during reload (https://github.com/jeverley/dscpclassify/issues/27)     _Thank you @Sam-arch99 for helping troubleshoot this._
* The service now creates a debug file `/tmp/dscpclassify.debug` when start/reload fails 
* Use ct_processed bit rather than relying on first reply packet for established_connection counting, this allows consideration of connections established before the service started (https://github.com/jeverley/dscpclassify/issues/26)
* Optimised loopback match @ldir-EDB0 (https://github.com/jeverley/dscpclassify/commit/c9b53e94af8bc7b0ed7eb928254f5f32b41de516)
* Improved service reload performance

## Addresses issues
- https://github.com/jeverley/dscpclassify/issues/27
- https://github.com/jeverley/dscpclassify/issues/26

diff --git a/etc/init.d/dscpclassify b/etc/init.d/dscpclassify
--- a/etc/init.d/dscpclassify
+++ b/etc/init.d/dscpclassify
@@ -1,40 +1,71 @@
 #!/bin/sh /etc/rc.common
 # shellcheck disable=SC3043,SC3003,SC2019,SC2018,SC3020,SC3057
 
-START=20
+START=50
 USE_PROCD=1
-DEBUG=0
+
+DEBUG_FILE="/tmp/dscpclassify.debug"
+INCLUDES_PATH="/tmp/etc/dscpclassify.d"
+PRE_INCLUDE="${INCLUDES_PATH}/pre-include.nft"
+POST_INCLUDE="${INCLUDES_PATH}/post-include.nft"
+
+MAIN="/etc/dscpclassify.d/main.nft"
+VERDICTS="/etc/dscpclassify.d/verdicts.nft"
+MAPS="/etc/dscpclassify.d/maps.nft"
+
+debug=1
+nft_result=""
 
 log() {
 	logger -t dscpclassify -p "daemon.$1" "$2"
+	case "$1" in
+	warning | err) echo "$2" ;;
+	esac
 }
 
-create_path() {
-	mkdir -p "$1" && return 0
-	log err "Unable to create '$1' path"
-	return 1
+create_debug_file() {
+	{
+		echo "dscpclassify ${action}: $(date)"
+		echo $'\n'"<--- ${PRE_INCLUDE} --->"
+		[ -f "$PRE_INCLUDE" ] && cat "$PRE_INCLUDE"
+		echo $'\n'"<--- ${POST_INCLUDE} --->"
+		[ -f "$POST_INCLUDE" ] && cat "$POST_INCLUDE"
+		echo $'\n'"<--- nft -f ${MAIN} --->"
+		echo "$nft_result"
+		echo $'\n'"<--- nft list table inet dscpclassify --->"
+		nft list table inet dscpclassify 2>&1
+	} > "$DEBUG_FILE"
+}
+
+delete_debug_file() {
+	rm -f "$DEBUG_FILE"
 }
 
 delete_includes() {
-	rm -f "/tmp/etc/dscpclassify-pre.include"
-	rm -f "/tmp/etc/dscpclassify-post.include"
+	rm -rf "$INCLUDES_PATH"
 }
 
-delete_table() {
-	nft delete table inet dscpclassify 2>/dev/null
+destroy_table() {
+	nft destroy table inet dscpclassify &>/dev/null
 }
 
-cleanup() {
+cleanup_service() {
+	destroy_table
+	delete_debug_file
 	delete_includes
-	delete_table
+}
+
+cleanup_setup() {
+	delete_debug_file
+	delete_includes
 }
 
 pre_include() {
-	echo "$1" >>"/tmp/etc/dscpclassify-pre.include"
+	echo "$1" >>"$PRE_INCLUDE"
 }
 
 post_include() {
-	echo "$1" >>"/tmp/etc/dscpclassify-post.include"
+	echo "$1" >>"$POST_INCLUDE"
 }
 
 list_append() {
@@ -338,7 +369,7 @@ create_user_set() {
 	parse_set_flags || return 1
 
 	check_set_against_existing "$name" "$type" "$comment" "$size" "$flags" "$timeout" || {
-		[ "$?" = 1 ] && post_include "delete set inet dscpclassify $name"
+		[ "$?" = 1 ] && post_include "destroy set inet dscpclassify $name"
 		post_include "add set inet dscpclassify $name { type $type; ${timeout:+timeout $timeout;} ${size:+size $size;} ${flags:+flags $flags;} ${auto_merge:+auto-merge;} ${comment:+comment \"$comment\";} }"
 	}
 
@@ -591,13 +622,19 @@ create_threaded_client_rule() {
 		return 1
 	}
 
+	check_set_exists tc_detect && post_include "destroy set inet dscpclassify tc_detect"
 	post_include "add rule inet dscpclassify established_connection meter tc_detect { ip daddr . th dport . meta l4proto timeout 5s limit rate over $((threaded_client_min_connections - 1))/minute } add @threaded_clients { ip daddr . th dport . meta l4proto timeout 30s }"
+	check_set_exists tc_detect6 && post_include "destroy set inet dscpclassify tc_detect6"
 	post_include "add rule inet dscpclassify established_connection meter tc_detect6 { ip6 daddr . th dport . meta l4proto timeout 5s limit rate over $((threaded_client_min_connections - 1))/minute } add @threaded_clients6 { ip6 daddr . th dport . meta l4proto timeout 30s }"
 
+	check_set_exists tc_orig_bulk && post_include "destroy set inet dscpclassify tc_orig_bulk"
 	post_include "add rule inet dscpclassify threaded_client meter tc_orig_bulk { ip saddr . th sport . meta l4proto timeout 5m limit rate over $((threaded_client_min_bytes - 1)) bytes/hour } update @threaded_clients { ip saddr . th sport . meta l4proto timeout 5m } goto ct_set_$class_bulk"
+	check_set_exists tc_orig_bulk6 && post_include "destroy set inet dscpclassify tc_orig_bulk6"
 	post_include "add rule inet dscpclassify threaded_client meter tc_orig_bulk6 { ip6 saddr . th sport . meta l4proto timeout 5m limit rate over $((threaded_client_min_bytes - 1)) bytes/hour } update @threaded_clients6 { ip6 saddr . th sport . meta l4proto timeout 5m } goto ct_set_$class_bulk"
 
+	check_set_exists tc_reply_bulk && post_include "destroy set inet dscpclassify tc_reply_bulk"
 	post_include "add rule inet dscpclassify threaded_client_reply meter tc_reply_bulk { ip daddr . th dport . meta l4proto timeout 5m limit rate over $((threaded_client_min_bytes - 1)) bytes/hour } update @threaded_clients { ip daddr . th dport . meta l4proto timeout 5m } goto ct_set_$class_bulk"
+	check_set_exists tc_reply_bulk6 && post_include "destroy set inet dscpclassify tc_reply_bulk6"
 	post_include "add rule inet dscpclassify threaded_client_reply meter tc_reply_bulk6 { ip6 daddr . th dport . meta l4proto timeout 5m limit rate over $((threaded_client_min_bytes - 1)) bytes/hour } update @threaded_clients6 { ip6 daddr . th dport . meta l4proto timeout 5m } goto ct_set_$class_bulk"
 }
 
@@ -620,7 +657,9 @@ create_threaded_service_rule() {
 		return 1
 	}
 
+	check_set_exists ts_detect && post_include "destroy set inet dscpclassify ts_detect"
 	post_include "add rule inet dscpclassify established_connection meter ts_detect { ip daddr . ip saddr and 255.255.255.0 . th sport . meta l4proto timeout 5s limit rate over $((threaded_service_min_connections - 1))/minute } add @threaded_services { ip daddr . ip saddr and 255.255.255.0 . th sport . meta l4proto timeout 30s }"
+	check_set_exists ts_detect6 && post_include "destroy set inet dscpclassify ts_detect6"
 	post_include "add rule inet dscpclassify established_connection meter ts_detect6 { ip6 daddr . ip6 saddr and ffff:ffff:ffff:: . th sport . meta l4proto timeout 5s limit rate over $((threaded_service_min_connections - 1))/minute } add @threaded_services6 { ip6 daddr . ip6 saddr and ffff:ffff:ffff:: . th sport . meta l4proto timeout 30s }"
 
 	post_include "add rule inet dscpclassify threaded_service ct original bytes < $threaded_service_min_bytes return"
@@ -644,21 +683,35 @@ create_dscp_mark_rule() {
 	post_include "add rule inet dscpclassify postrouting ct mark and \$ct_dscp vmap @ct_dscp"
 }
 
+create_flush_actions() {
+	for chain in $(nft -j list chains | jsonfilter -e '@.nftables[@.chain.table="dscpclassify"].chain.name'); do
+		pre_include "flush chain inet dscpclassify ${chain}"
+	done
+	for map in $(nft -j list maps | jsonfilter -e '@.nftables[@.map.table="dscpclassify"].map.name'); do
+		pre_include "flush map inet dscpclassify ${map}"
+	done
+}
+
 create_pre_include() {
+	rm -f "$PRE_INCLUDE"
+
 	pre_include "define lan = { $(mklist "$lan" ", " "\"") }"
 	pre_include "define wan = { $(mklist "$wan" ", " "\"") }"
 
+	[ "$action" = "reload" ] && create_flush_actions 
 	pre_include "add table inet dscpclassify"
 	check_set_exists threaded_clients || pre_include "add set inet dscpclassify threaded_clients { type ipv4_addr . inet_service . inet_proto; flags timeout; }"
 	check_set_exists threaded_clients6 || pre_include "add set inet dscpclassify threaded_clients6 { type ipv6_addr . inet_service . inet_proto; flags timeout; }"
 	check_set_exists threaded_services || pre_include "add set inet dscpclassify threaded_services { type ipv4_addr . ipv4_addr . inet_service . inet_proto; flags timeout; }"
 	check_set_exists threaded_services6 || pre_include "add set inet dscpclassify threaded_services6 { type ipv6_addr . ipv6_addr . inet_service . inet_proto; flags timeout; }"
 
-	pre_include "include \"/etc/dscpclassify.d/verdicts.nft\""
-	pre_include "include \"/etc/dscpclassify.d/maps.nft\""
+	pre_include "include \"${VERDICTS}\""
+	pre_include "include \"${MAPS}\""
 }
 
 create_post_include() {
+	rm -f "$POST_INCLUDE"
+
 	create_client_hints_rule || return 1
 
 	config_foreach create_user_set set   # depreciating in favour of 'ipset' section name for consistency with fw4
@@ -669,15 +722,6 @@ create_post_include() {
 	create_threaded_service_rule || return 1
 
 	create_dscp_mark_rule || return 1
-}
-
-flush_table() {
-	for i in $(nft -j list chains | jsonfilter -e '@.nftables[@.chain.table="dscpclassify"].chain.name'); do
-		nft flush chain inet dscpclassify "$i"
-	done
-	for i in $(nft -j list maps | jsonfilter -e '@.nftables[@.map.table="dscpclassify"].map.name'); do
-		nft flush map inet dscpclassify "$i"
-	done
 }
 
 get_zones() {
@@ -701,54 +745,74 @@ get_zones() {
 }
 
 setup() {
-	local action lan wan
+	local lan wan
 
-	delete_includes
-	action="$1"
+	cleanup_setup
 
-	config_load dscpclassify || return 1
-	config_get_bool DEBUG global debug "$DEBUG"
+	config_load dscpclassify || {
+		log err "Failed to load config file"
+		return 1
+	}
+	config_get_bool debug global debug "$debug"
 
-	get_zones || return 0
+	get_zones || {
+		log notice "Deferring ${action} because lan/wan firewall zones are unavailable"
+		return 0
+	}
 
-	[ "$action" = "start" ] && delete_table
+	[ "$action" = "start" ] && destroy_table
 
-	create_path "/tmp/etc" || return 1
-	create_pre_include || return 1
-	create_post_include || return 1
+	mkdir -p "$INCLUDES_PATH" || {
+		log err "Failed to create path: ${INCLUDES_PATH}"
+		return 1
+	}
+	create_pre_include || {
+		log err "Failed to create pre-include rules"
+		return 1
+	}
+	create_post_include || {
+		log err "Failed to create post-include rules"
+		return 1
+	}
 
-	[ "$action" = "reload" ] && flush_table
+	nft_result="$(nft -f "$MAIN" 2>&1)" || {
+		log err "Failed to load main.nft with status: $?"
+		return 1
+	}
 
-	nft -f "/etc/dscpclassify.d/main.nft" || return 1
-	[ "$DEBUG" != 1 ] && delete_includes
-
+	log notice "Service ${action}ed"
 	return 0
 }
 
+setup_failed() {
+	log warning "Service ${action} failed"
+	[ "$debug" = 1 ] && create_debug_file
+	destroy_table
+	delete_includes
+}
+
 start_service() {
-	setup start || {
-		log err "Service start failed"
-		[ "$DEBUG" != 1 ] && cleanup
+	setup || {
+		setup_failed
 		return 1
 	}
-	log notice "Service started"
+	cleanup_setup
 }
 
 reload_service() {
 	/etc/init.d/dscpclassify status &>/dev/null || {
-		echo "The dscpclassify service does not appear to be loaded."
+		echo "The dscpclassify service is not loaded"
 		return 1
 	}
 
-	setup reload || {
-		log err "Service reload failed"
-		[ "$DEBUG" != 1 ] && cleanup
+	setup || {
+		setup_failed
 		return 1
 	}
-	log notice "Service reloaded"
+	cleanup_setup
 }
 
 stop_service() {
-	cleanup
+	cleanup_service
 	log notice "Service stopped"
 }
