Implement ipset family detection and entry family validation

diff --git a/etc/init.d/dscpclassify b/etc/init.d/dscpclassify
--- a/etc/init.d/dscpclassify
+++ b/etc/init.d/dscpclassify
@@ -402,6 +402,7 @@ parse_rule_ips() {
 		return 2
 	}
 
+        # shellcheck disable=SC2086
 	for i in $(printf '%s\n' $addresses | sort -u); do
 		# ipv4 address
 		check_addr4 "$i" && {
@@ -526,22 +527,45 @@ parse_set_loadfile() {
 		return 1
 	}
 
-	while IFS= read -r addr || [ -n "$addr" ]; do
-		addr=$(echo "$addr" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
-		[ -n "$addr" ] || continue
+	while IFS= read -r entry || [ -n "$entry" ]; do
+		entry=$(echo "$entry" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
+		[ -n "$entry" ] || continue
 
-		check_addr "$addr" "$family" || {
-			log warning "The ${family:+$family }loadfile address ${addr} is invalid"
+		check_addr "$entry" "$family" || {
+			log warning "The ${family:+$family }loadfile address ${entry} is invalid"
 			continue
 		}
-		loadfile_addr="${loadfile_addr:+$loadfile_addr }$addr"
+		loadfile_entries="${loadfile_entries:+$loadfile_entries }$entry"
 	done < "$loadfile"
 	return 0
 }
 
+determine_set_family() {
+	local addresses="$1" _family="$family"
+	for addr in $addresses; do
+		local addr_family
+		if check_addr4 "$addr"; then
+			addr_family="ipv4"
+		elif check_addr6 "$addr"; then
+			addr_family="ipv6"
+		else
+			log warning "ipset {$name:+$name }contains an invalid address: $addr"
+			continue
+		fi
+		if [ -z "$_family" ]; then
+			_family="$addr_family"
+		elif [ "$_family" != "$addr_family" ]; then
+			log warning "ipset {$name:+$name }contains both IPv4 and IPv6 addresses"
+			return 1
+		fi
+	done
+	[ -n "$_family" ] || return 1
+	family="$_family"
+}
+
 create_user_set() {
 	local section="$1"
-	local comment entry element enabled family flags match size name timeout type loadfile loadfile_addr
+	local comment entries enabled family flags match size name timeout type loadfile loadfile_entries
 	local flag_constant flag_interval flag_timeout auto_merge
 	local error=0
 
@@ -560,16 +584,21 @@ create_user_set() {
 	config_get_bool flag_interval "$section" interval
 	
 	config_get loadfile "$section" loadfile
-	config_get entry "$section" entry
+	config_get entries "$section" entry
 
 	check_set_name "$name" || error=1
 	check_set_size "$size" || error=1
-	check_family "$family" || {
-		log warning "Set contains an invalid family"
+
+	if [ -n "$family" ] && ! check_family "$family"; then
+		log warning "ipset {$name:+$name }contains an invalid family"
+		error=1
+	fi
+	parse_set_loadfile || error=1
+	determine_set_family "$entries $loadfile_entries" || {
+		log warning "Could not determine the family of ipset{$name:+ $name}"
 		error=1
 	}
 
-	parse_set_loadfile || error=1
 	parse_set_type || error=1
 	parse_set_timeout || error=1
 	parse_set_flags || error=1
@@ -580,7 +609,7 @@ create_user_set() {
 		post_include "add set inet $TABLE $name { type $type; ${timeout:+timeout $timeout;} ${size:+size $size;} ${flags:+flags $flags;} ${auto_merge:+auto-merge;} ${comment:+comment \"$comment\";} }"
 	}
 
-	[ -n "$entry$loadfile_addr" ] && post_include "add element inet $TABLE $name $(nft_element_list "$entry $loadfile_addr")"
+	[ -n "$entries$loadfile_entries" ] && post_include "add element inet $TABLE $name $(nft_element_list "$entries $loadfile_entries")"
 
 	# Store set type for use in user rules
 	case $family in
@@ -682,18 +711,22 @@ rule_addr() {
 	[ -n "$addresses" ] || return 0
 
 	if [ -n "$family" ] && ! check_family "$family"; then
+	        # shellcheck disable=SC2016
 		log warning "Rule ${name:+'$name '}contains an invalid family"
 		return 1
 	fi
 	parse_rule_ips "$addresses" || {
+	        # shellcheck disable=SC2016
 		log warning "Rule ${name:+'$name '}contains an invalid ${direction}_ip"
 		return 1
 	}
 	if [ -n "$ipv4$ipv4_negate$ipset$ipset_negate" ] && [ "$family" = "ipv6" ]; then
+	        # shellcheck disable=SC2016
 		log warning "Rules cannot combine an ipv4 ${direction}_ip with the 'ipv6' family option${name:+, rule: '$name'}"
 		return 1
 	fi
 	if [ -n "$ipv6$ipv6_negate$ipset6$ipset_negate6" ] && [ "$family" = "ipv4" ]; then
+	        # shellcheck disable=SC2016
 		log warning "Rules cannot combine an ipv6 ${direction}_ip with the 'ipv4' family option${name:+, rule: '$name'}"
 		return 1
 	fi
