Augment the loadfile parsing to check for and exclude invalid values

diff --git a/etc/init.d/dscpclassify b/etc/init.d/dscpclassify
--- a/etc/init.d/dscpclassify
+++ b/etc/init.d/dscpclassify
@@ -353,6 +353,38 @@ parse_set_type() {
 	return 0
 }
 
+is_valid_ip_or_cidr() {
+	local ip_or_cidr="$1"
+
+	# This regex matches both IPv4 and IPv6 addresses, as well as CIDR notation. IPv6 condensed addresses
+	# are also supported. The regex is quite complex, but it ensures that the input is a valid IP address or CIDR.
+	if echo "$ip_or_cidr" | grep -q -E -e "((^\h*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\h*(|\/([0-9]|[1-2][0-9]|3[0-2]))$)|(^\h*((([0-9a-f]{1,4}:){7}([0-9a-f]{1,4}|:))|(([0-9a-f]{1,4}:){6}(:[0-9a-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9a-f]{1,4}:){5}(((:[0-9a-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9a-f]{1,4}:){4}(((:[0-9a-f]{1,4}){1,3})|((:[0-9a-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9a-f]{1,4}:){3}(((:[0-9a-f]{1,4}){1,4})|((:[0-9a-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9a-f]{1,4}:){2}(((:[0-9a-f]{1,4}){1,5})|((:[0-9a-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9a-f]{1,4}:){1}(((:[0-9a-f]{1,4}){1,6})|((:[0-9a-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9a-f]{1,4}){1,7})|((:[0-9a-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\h*(|\/([0-9]|[0-9][0-9]|1[0-1][0-9]|12[0-8]))$))"; then
+		# Valid IPv4/6 address or CIDR format
+		return 0
+	fi
+
+	# Invalid IP or CIDR
+	return 1
+}
+
+get_valid_ips_in_file() {
+	local file="$1"
+	local valid_ips=""
+
+	[ -f "$file" ] || {
+		log err "File not found: $file"
+		return 1
+	}
+
+	while IFS= read -r line || [ -n "$line" ]; do
+		if is_valid_ip_or_cidr "$line"; then
+			valid_ips="${valid_ips:+$valid_ips }$line"
+		fi
+	done < "$file"
+
+	echo "$valid_ips"
+}
+
 create_user_set() {
 	local comment entry element enabled family flags match size name timeout type loadfile loadfile_entry
 	local flag_constant flag_interval flag_timeout auto_merge
@@ -393,8 +425,14 @@ create_user_set() {
 	}
 
 	if [ -n "$loadfile" ]; then
-		log notice "Loading $loadfile for rule name: $name"
-		loadfile_entry=$(cat "$loadfile") || return 1
+		log notice "Parsing IPs in $loadfile for rule name: $name"
+		loadfile_entry=$(get_valid_ips_in_file "$loadfile") || return 1
+
+		loadfile_line_count=$(wc -l < "$loadfile")
+		valid_entry_count=$(echo "$loadfile_entry" | wc -w)
+		if [ "$loadfile_line_count" -ne "$valid_entry_count" ]; then
+			log warning "Invalid value was found in file '$loadfile' and was excluded from the set. Check the file for IP/CIDR errors."
+		fi
 	fi
 
 	[ -n "$entry$element$loadfile_entry" ] && post_include "add element inet dscpclassify $name { $(format_list "$entry $element $loadfile_entry" ", ") }"
