Execute reload flush actions as part of pre-include

diff --git a/etc/init.d/dscpclassify b/etc/init.d/dscpclassify
--- a/etc/init.d/dscpclassify
+++ b/etc/init.d/dscpclassify
@@ -4,9 +4,7 @@
 START=50
 USE_PROCD=1
 
-DEBUG=1
 DEBUG_FILE="/tmp/dscpclassify.debug"
-
 INCLUDES_PATH="/tmp/etc/dscpclassify.d"
 PRE_INCLUDE="${INCLUDES_PATH}/pre-include.nft"
 POST_INCLUDE="${INCLUDES_PATH}/post-include.nft"
@@ -15,13 +13,17 @@ MAIN="/etc/dscpclassify.d/main.nft"
 VERDICTS="/etc/dscpclassify.d/verdicts.nft"
 MAPS="/etc/dscpclassify.d/maps.nft"
 
+debug=1
+nft_result=""
+
 log() {
 	logger -t dscpclassify -p "daemon.$1" "$2"
-	[ "$DEBUG" = 1 ] && echo "$2"
+	case "$1" in
+	warning | err) echo "$2" ;;
+	esac
 }
 
 create_debug_file() {
-	local action="$1"
 	{
 		echo "dscpclassify ${action}: $(date)"
 		echo $'\n'"<--- ${PRE_INCLUDE} --->"
@@ -43,14 +45,14 @@ delete_includes() {
 	rm -rf "$INCLUDES_PATH"
 }
 
-delete_table() {
+destroy_table() {
 	nft destroy table inet dscpclassify &>/dev/null
 }
 
 cleanup_service() {
+	destroy_table
 	delete_debug_file
 	delete_includes
-	delete_table
 }
 
 cleanup_setup() {
@@ -681,12 +683,22 @@ create_dscp_mark_rule() {
 	post_include "add rule inet dscpclassify postrouting ct mark and \$ct_dscp vmap @ct_dscp"
 }
 
+create_flush_actions() {
+	for chain in $(nft -j list chains | jsonfilter -e '@.nftables[@.chain.table="dscpclassify"].chain.name'); do
+		pre_include "flush chain inet dscpclassify ${chain}"
+	done
+	for map in $(nft -j list maps | jsonfilter -e '@.nftables[@.map.table="dscpclassify"].map.name'); do
+		pre_include "flush map inet dscpclassify ${map}"
+	done
+}
+
 create_pre_include() {
 	rm -f "$PRE_INCLUDE"
 
 	pre_include "define lan = { $(mklist "$lan" ", " "\"") }"
 	pre_include "define wan = { $(mklist "$wan" ", " "\"") }"
 
+	[ "$action" = "reload" ] && create_flush_actions 
 	pre_include "add table inet dscpclassify"
 	check_set_exists threaded_clients || pre_include "add set inet dscpclassify threaded_clients { type ipv4_addr . inet_service . inet_proto; flags timeout; }"
 	check_set_exists threaded_clients6 || pre_include "add set inet dscpclassify threaded_clients6 { type ipv6_addr . inet_service . inet_proto; flags timeout; }"
@@ -712,15 +724,6 @@ create_post_include() {
 	create_dscp_mark_rule || return 1
 }
 
-flush_table() {
-	for i in $(nft -j list chains | jsonfilter -e '@.nftables[@.chain.table="dscpclassify"].chain.name'); do
-		nft flush chain inet dscpclassify "$i"
-	done
-	for i in $(nft -j list maps | jsonfilter -e '@.nftables[@.map.table="dscpclassify"].map.name'); do
-		nft flush map inet dscpclassify "$i"
-	done
-}
-
 get_zones() {
 	local dev lan_zones wan_zones
 
@@ -742,7 +745,6 @@ get_zones() {
 }
 
 setup() {
-	local action="$1"
 	local lan wan
 
 	cleanup_setup
@@ -751,14 +753,14 @@ setup() {
 		log err "Failed to load config file"
 		return 1
 	}
-	config_get_bool DEBUG global debug "$DEBUG"
+	config_get_bool debug global debug "$debug"
 
 	get_zones || {
 		log notice "Deferring ${action} because lan/wan firewall zones are unavailable"
 		return 0
 	}
 
-	[ "$action" = "start" ] && delete_table
+	[ "$action" = "start" ] && destroy_table
 
 	mkdir -p "$INCLUDES_PATH" || {
 		log err "Failed to create path: ${INCLUDES_PATH}"
@@ -773,8 +775,6 @@ setup() {
 		return 1
 	}
 
-	[ "$action" = "reload" ] && flush_table
-
 	nft_result="$(nft -f "$MAIN" 2>&1)" || {
 		log err "Failed to load main.nft with status: $?"
 		return 1
@@ -785,16 +785,15 @@ setup() {
 }
 
 setup_failed() {
-	local action="$1"
-	log err "Service ${action} failed"
-	[ "$DEBUG" = 1 ] && create_debug_file "$action"
+	log warning "Service ${action} failed"
+	[ "$debug" = 1 ] && create_debug_file
+	destroy_table
 	delete_includes
-	delete_table
 }
 
 start_service() {
-	setup start || {
-		setup_failed start
+	setup || {
+		setup_failed
 		return 1
 	}
 	cleanup_setup
@@ -802,12 +801,12 @@ start_service() {
 
 reload_service() {
 	/etc/init.d/dscpclassify status &>/dev/null || {
-		echo "The dscpclassify service is not loaded."
+		echo "The dscpclassify service is not loaded"
 		return 1
 	}
 
-	setup reload || {
-		setup_failed reload
+	setup || {
+		setup_failed
 		return 1
 	}
 	cleanup_setup
