Further code cleanups

diff --git a/etc/init.d/dscpclassify b/etc/init.d/dscpclassify
--- a/etc/init.d/dscpclassify
+++ b/etc/init.d/dscpclassify
@@ -232,9 +232,9 @@ addr() {
 	fi
 
 	[ -n "$ipv4" ] && rule="ip $xaddr { $(mklist "$ipv4") }"
-	[ -n "$ipv6" ] && rule6="ip6 $xaddr { $(mklist "$ipv6") }"
-
 	[ -n "$ipv4_negate" ] && rule="$rule ip $xaddr != { $(mklist "$ipv4_negate") }"
+
+	[ -n "$ipv6" ] && rule6="ip6 $xaddr { $(mklist "$ipv6") }"
 	[ -n "$ipv6_negate" ] && rule6="$rule6 ip6 $xaddr != { $(mklist "$ipv6_negate") }"
 
 	[ -n "$ipset$ipset_negate" ] && case $3 in
@@ -310,9 +310,9 @@ post_include() {
 
 create_user_set() {
 	local constant comment entry element enabled interval family flags match maxelem name timeout type
-
-	config_get_bool enabled "$1" enabled
-	[ "$enabled" = 0 ] && return 0
+	
+	config_get_bool enabled "$1" enabled 1
+	[ "$enabled" != 1 ] || return 0
 
 	config_get comment "$1" comment
 	config_get name "$1" name
@@ -326,6 +326,8 @@ create_user_set() {
 	config_get_bool constant "$1" constant
 	config_get_bool interval "$1" interval
 	config_get type "$1" type
+
+	[ -n "$element" ] && log warning "The user set 'element' option is being depreciated in favour of 'entry'"
 
 	if [ -z "$family$type" ] || [ -n "$family" ] && [ -n "$type" ]; then
 		log warning "Sets must contain either a family or type option"
@@ -367,8 +369,8 @@ create_user_rule() {
 	local enabled family proto direction device dest dest_ip dest_port src src_ip src_port counter class name
 	local nfproto l4proto oifname daddr daddr6 dport iifname saddr saddr6 sport verdict comment
 
-	config_get_bool enabled "$1" enabled
-	[ "$enabled" = 0 ] && return 0
+	config_get_bool enabled "$1" enabled 1
+	[ "$enabled" != 1 ] || return 0
 
 	config_get family "$1" family
 	config_get proto "$1" proto
@@ -424,12 +426,12 @@ create_threaded_client_rule() {
 	local class_bulk threaded_client_min_bytes
 
 	config_get_uint threaded_client_min_bytes global threaded_client_min_bytes 10000 || {
-		log error "Global option threaded_client_min_bytes contains an invalid number"
+		log err "Global option threaded_client_min_bytes contains an invalid number"
 		return 1
 	}
 	config_get class_bulk global class_bulk le
 	class_bulk="$(check_class "$class_bulk")" || {
-		log error "Global option class_bulk contains an invalid DSCP class"
+		log err "Global option class_bulk contains an invalid DSCP class"
 		return 1
 	}
 
@@ -444,12 +446,12 @@ create_threaded_service_rule() {
 	local class_high_throughput threaded_service_min_bytes
 
 	config_get_uint threaded_service_min_bytes global threaded_service_min_bytes 1000000 || {
-		log error "Global option threaded_service_min_bytes contains an invalid number"
+		log err "Global option threaded_service_min_bytes contains an invalid number"
 		return 1
 	}
 	config_get class_high_throughput global class_high_throughput af13
 	class_high_throughput="$(check_class "$class_high_throughput")" || {
-		log error "Global option class_high_throughput contains an invalid DSCP class"
+		log err "Global option class_high_throughput contains an invalid DSCP class"
 		return 1
 	}
 
@@ -518,7 +520,7 @@ start_service() {
 	nft delete table inet dscpclassify 2>/dev/null
 
 	setup || {
-		log error "Service start failed"
+		log err "Service start failed"
 		return 1
 	}
 	log notice "Service started"
@@ -533,7 +535,7 @@ reload_service() {
 	done
 
 	setup || {
-		log error "Service reload failed"
+		log err "Service reload failed"
 		return 1
 	}
 	log notice "Service reloaded"
