Additional logging for setup function errors
Debug option now creates a single file `/tmp/dscpclassify.debug`

Update main.nft to use new include path

diff --git a/etc/init.d/dscpclassify b/etc/init.d/dscpclassify
--- a/etc/init.d/dscpclassify
+++ b/etc/init.d/dscpclassify
@@ -3,38 +3,66 @@
 
 START=20
 USE_PROCD=1
-DEBUG=0
+
+DEBUG=1
+DEBUG_FILE="/tmp/dscpclassify.debug"
+
+INCLUDES_PATH="/tmp/etc/dscpclassify.d"
+PRE_INCLUDE="${INCLUDES_PATH}/pre-include.nft"
+POST_INCLUDE="${INCLUDES_PATH}/post-include.nft"
+
+MAIN="/etc/dscpclassify.d/main.nft"
+VERDICTS="/etc/dscpclassify.d/verdicts.nft"
+MAPS="/etc/dscpclassify.d/maps.nft"
 
 log() {
 	logger -t dscpclassify -p "daemon.$1" "$2"
 }
 
-create_path() {
-	mkdir -p "$1" && return 0
-	log err "Unable to create '$1' path"
-	return 1
+create_debug_file() {
+	local action="$1"
+	{
+		echo "dscpclassify ${action}: $(date)"
+		echo $'\n'"<--- ${PRE_INCLUDE} --->"
+		[ -f "$PRE_INCLUDE" ] && cat "$PRE_INCLUDE"
+		echo $'\n'"<--- ${POST_INCLUDE} --->"
+		[ -f "$POST_INCLUDE" ] && cat "$POST_INCLUDE"
+		echo $'\n'"<--- nft -f ${MAIN} --->"
+		echo "$nft_result"
+		echo $'\n'"<--- nft list table inet dscpclassify --->"
+		nft list table inet dscpclassify 2>&1
+	} > "$DEBUG_FILE"
+}
+
+delete_debug_file() {
+	rm -f "$DEBUG_FILE"
 }
 
 delete_includes() {
-	rm -f "/tmp/etc/dscpclassify-pre.include"
-	rm -f "/tmp/etc/dscpclassify-post.include"
+	rm -rf "$INCLUDES_PATH"
 }
 
 delete_table() {
 	nft delete table inet dscpclassify 2>/dev/null
 }
 
-cleanup() {
+cleanup_service() {
+	delete_debug_file
 	delete_includes
 	delete_table
 }
 
+cleanup_setup() {
+	delete_debug_file
+	delete_includes
+}
+
 pre_include() {
-	echo "$1" >>"/tmp/etc/dscpclassify-pre.include"
+	echo "$1" >>"$PRE_INCLUDE"
 }
 
 post_include() {
-	echo "$1" >>"/tmp/etc/dscpclassify-post.include"
+	echo "$1" >>"$POST_INCLUDE"
 }
 
 list_append() {
@@ -645,6 +673,8 @@ create_dscp_mark_rule() {
 }
 
 create_pre_include() {
+	rm -f "$PRE_INCLUDE"
+
 	pre_include "define lan = { $(mklist "$lan" ", " "\"") }"
 	pre_include "define wan = { $(mklist "$wan" ", " "\"") }"
 
@@ -654,11 +684,13 @@ create_pre_include() {
 	check_set_exists threaded_services || pre_include "add set inet dscpclassify threaded_services { type ipv4_addr . ipv4_addr . inet_service . inet_proto; flags timeout; }"
 	check_set_exists threaded_services6 || pre_include "add set inet dscpclassify threaded_services6 { type ipv6_addr . ipv6_addr . inet_service . inet_proto; flags timeout; }"
 
-	pre_include "include \"/etc/dscpclassify.d/verdicts.nft\""
-	pre_include "include \"/etc/dscpclassify.d/maps.nft\""
+	pre_include "include \"${VERDICTS}\""
+	pre_include "include \"${MAPS}\""
 }
 
 create_post_include() {
+	rm -f "$POST_INCLUDE"
+
 	create_client_hints_rule || return 1
 
 	config_foreach create_user_set set   # depreciating in favour of 'ipset' section name for consistency with fw4
@@ -701,54 +733,79 @@ get_zones() {
 }
 
 setup() {
-	local action lan wan
+	local action="$1"
+	local lan wan
 
-	delete_includes
-	action="$1"
+	cleanup_setup
 
-	config_load dscpclassify || return 1
+	config_load dscpclassify || {
+		log err "Failed to load config file"
+		return 1
+	}
 	config_get_bool DEBUG global debug "$DEBUG"
 
-	get_zones || return 0
+	get_zones || {
+		log notice "Deferring ${action} because lan/wan firewall zones are unavailable"
+		return 0
+	}
 
 	[ "$action" = "start" ] && delete_table
 
-	create_path "/tmp/etc" || return 1
-	create_pre_include || return 1
-	create_post_include || return 1
+	mkdir -p "$INCLUDES_PATH" || {
+		log err "Failed to create path: ${INCLUDES_PATH}"
+		return 1
+	}
+	create_pre_include || {
+		log err "Failed to create pre-include rules"
+		return 1
+	}
+	create_post_include || {
+		log err "Failed to create post-include rules"
+		return 1
+	}
 
 	[ "$action" = "reload" ] && flush_table
 
-	nft -f "/etc/dscpclassify.d/main.nft" || return 1
-	[ "$DEBUG" != 1 ] && delete_includes
+	nft_result="$(nft -f "$MAIN" 2>&1)"
+	nft -f "$MAIN" || {
+		log err "Failed to load main.nft with status: $?"
+		return 1
+	}
 
+	log notice "Service ${action}ed"
 	return 0
+}
+
+setup_failed() {
+	local action="$1"
+	log err "Service ${action} failed"
+	[ "$DEBUG" = 1 ] && create_debug_file "$action"
+	delete_includes
+	delete_table
 }
 
 start_service() {
 	setup start || {
-		log err "Service start failed"
-		[ "$DEBUG" != 1 ] && cleanup
+		setup_failed start
 		return 1
 	}
-	log notice "Service started"
+	cleanup_setup
 }
 
 reload_service() {
 	/etc/init.d/dscpclassify status &>/dev/null || {
-		echo "The dscpclassify service does not appear to be loaded."
+		echo "The dscpclassify service is not loaded."
 		return 1
 	}
 
 	setup reload || {
-		log err "Service reload failed"
-		[ "$DEBUG" != 1 ] && cleanup
+		setup_failed reload
 		return 1
 	}
-	log notice "Service reloaded"
+	cleanup_setup
 }
 
 stop_service() {
-	cleanup
+	cleanup_service
 	log notice "Service stopped"
 }
